MCU = STM32F401
BOARD = GENERIC_STM32_F401XC
BOOTLOADER = tinyuf2

LTO_ENABLE = yes
BOOTMAGIC_ENABLE = no
ENCODER_ENABLE = no
UARTENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
NKRO_ENABLE = no
RGBLIGHT_ENABLE = no
WS2812_DRIVER = pwm
RGB_MATRIX_ENABLE = no
HAPTIC_ENABLE = no
OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=TRUE
